docker push poestat/psbase38py3:latest
docker push poestat/psbase39py3:latest
docker push poestat/psbase310py3:latest
docker push poestat/psdatabase:latest
docker push poestat/psnginx:latest
docker push poestat/pspgbounce:latest
docker push poestat/psredis:latest
docker push poestat/psserver:latest
docker push poestat/pswebapp:latest
